# Define the Loggers
logger_defaults: &logger_defaults
  level: ALL
  trace: true
  additive: false
  outputters:
  - papertrail

loggers:

- name: Process::Naf::Runner
  <<: *logger_defaults

- name: Process::Naf::Runner::Af::AdvisoryLocker
  <<: *logger_defaults

- name: MyScript
  <<: *logger_defaults

outputters:

- type  : StdoutOutputter
  name  : stdout
  level : ALL
  formatter:
    pattern     : '%c (PID: %p) %l: %m'
    type        : PatternFormatter

# If you are using Papertrail use the following
# Log4r Outputter definition, and change LOGGING_PORT
# to the port of your logging destination

# Make sure that your pattern format has the substring:  'PID: %p'
# or else it will not be found by Naf's links!
#
#- type: RemoteSyslogOutputter
#  name: papertrail
#  level: ALL
#  url: syslog://logs.papertrailapp.com:LOGGING_PORT
#  program: My_Program
#  formatter:
#    pattern     : '%c (PID: %p) %l: %m'
#    type        : PatternFormatter